version: '3'
services:

  apache:
    container_name: url-redirector
    image: httpd:latest

    volumes:
      - ./conf:/usr/local/apache2/conf
      - ./htdocs:/usr/local/apache2/htdocs
      - ./cgi-bin:/usr/local/apache2/cgi-bin

    networks:
      default:
#        ipv4_address: 172.21.0.3

networks:
  default:
    external: true
    name: nginx-pm
